#+STARTUP: overview

* 1.Master Librarians

Jack stared out the kitchen window.

The sun was not up yet. But the sky was growing light.

Jack had been awake for a long time.

He had been thinking about the dream he'd had--

the dream about Morgan le Fay.

The tree house is back, Morgan had said. I'm waiting.

Jack wished that dreams were real.

He missed Morgan's magic tree house.

"Jack!" His little sister Annie appeared in the doorway.

"We have to go to the woods now!" she said.

"Why?" Jack asked.

"I had a dream about Morgan!" exclaimed[ iksˈkleimd ]

Annie.

"She said the tree house is back and she's waiting for us!"

"That was my dream," said Jack.

He raced up the stairs[ steəz ].

Having the same dream must mean something, he thought.

He grabbed his backpack and threw his notebook and pencil

into it.

Then he ran downstairs[ ˌdaʊnˈsteəz ].

"We'll be back soon, Mom!" Jack called into the living

room.

"Where you going so early?" his dad called.

"Just for a quick walk!" said Jack.

"It rained last night," called his mom.

"Don't get your shoes wet."

"We won't!"

Jack slipped out the door.

Annie was waiting for him.

"Let's go!" she said.

The sky was pale[ peɪl ] gray.

The air felt freshly washed.

Jack and Annie ran up their quiet street to the

Frog Creek woods.

They headed between the trees. Soon they came to the

tallest oak[ əʊk ] in the woods.

There was a wooden house high in the treetop.

"It is back!" whispered[ 'wɪspəd ] Jack.

Someone looked out the window of the tree house-

a lovely old woman with long white hair. Morgan le Fay.

"Come up," called the magical librarian.

Jack and Annie climbed up to the rope ladder and

into the tree house.

In the dawn light, they stared at Morgan le Fay.

She looked beautiful in a red velvet[ ˈvelvɪt ]

robe[ rəʊb ].

Jack pushed his glasses into place. He couldn't stop

smiling.

"We both had dreams about you!" said Annie.

"I know," said Morgan.

"You do?"

"Yes, I sent them to you," said Morgan, "because I need

your help."

"What kind of help?" said Jack.

"Merlin the Magician[ məˈdʒɪʃn ] has been up to his

tricks[ trɪks ] again," said Morgan.

"So I haven't had any time to collect books for

Camelot's library."

"Can we collect them for you?" asked Annie.

"Yes, but in order to gather[ ˈgæðə(r) ] books through

time you must be Master Librarians," said Morgan,

"if you pass the test."

"Really?" said Annie.

"What kind of test?" Jack asked.

"You must show that you know how to do research," said

Morgan, "and show that you can find answers to hard

questions."

"How?" said Annie.

"By solving four riddles[ 'rɪdlz ]," said Morgan.

She reached into the folds of her robe[ rəʊb ] and

pulled out a rolled-up[ 'rəʊld'ʌp ] paper.

"The first riddle[ ˈrɪdl ] is writeen on this

ancient[ ˈeɪnʃənt ] scroll[ skrəʊl ]," she said.

"This book will help you find the answer."

She held out a book. On the cover were the words

Ocean[ ˈəʊʃn ] Guide[ gaɪd ].

"This is where you have to go," said Morgan.

"The ocean! Oh, boy!" said Annie.

She pointed at the cover.

"I wish we--"

"Stop!" Jack grabbed Annie's hand.

"How will we know if we've found the right answer to

riddle?" he asked Morgan.

"You will know," Morgan said

mysteriously[ mɪ'stɪərɪəslɪ ].

"I promise you will know."

Jack let go of Annie's hand.

She pointed again at the cover and finished her wish:

"I wish we could go there."

The wind started to blow.

"Are you coming with us, Morgan?" Jack said.

Before Morgan could answer, the tree house started to

spin.

Jack squeezed[ skwi:zd ] his eyes shut.

The tree house spun faster and faster.

Then everything was still.

Absolutely still.

Jack open his eyes.

Morgan le Fay was gone.

Only the ancient scroll and the ocean book were left

in her place.




* 2.The Reef[ ri:f ]
  A breeze[ bri:z ] blew through the window.

  Sea gulls[ 'ɡʌlz ] cried. Waves lapped[ læpt ]

  the shore[ ʃɔ:(r) ].

  Annie picked up the riddle[ ˈrɪdl ] scroll.

  She unrolled it. Together she and Jack read the riddle:

  Rough[ rʌf ] and gray as rock,
  I'm plain[ pleɪn ] as plain can be.
  But hidden deep inside
  There's great beauty in me.
  What am I?

  "Let's find the answer," said Annie.

  She and Jack looked out the window.

  The tree house wasn't in a tree.

  It was on the ground.

  "Why is the ground pink?" said Jack.

  "I don't know," said Annie. "But I'm going out there"

  "I'm going to do a little research first," said Jack.

  Annie climbed out of the tree house.

  Jack picked up the ocean[ ˈəʊʃn ] book and

  flipped[ flipt ] through it.

  He found a picture of a pink island surrounded by water.

  He read:

  This is a coral[ ˈkɒrəl ] reef[ ri:f ].
  Coral are tiny sea animals. After they
  die, their skeletons[ ˈskelitnz ] remain.
  Over time, the reef builds up from stacks[ stæks ]
  of coral skeletons.

  "Oh,man, tiny skeletons," said Jack.

  He pulled out his notebook and wrote:

  Millions of coral skelitons.

  "Jack! Jack! Come back at this," cried Annie.

  "What is it?"

  "I don't know. But you'll love it!" she said.

  Jack threw his notebook and ocean book into his pack.

  He climbed out the window.

  "Is it the answer to the riddle?" he called.

  "I don't think so. It doesn't look very plain," said

  Annie.

  She was standing at the edge of the watch.

  Beside her was a strange[ streɪndʒ ]-looking machine.

  Jack hurried over the bumpy[ ˈbʌmpi ] coral to get a

  better look.

  The machine was half on the reef and half in the

  clear bulue water.

  It looked like a huge white bubble[ ˈbʌbl ] with a big

  window.

  "Is ti a special kind of boat?" asked Annie.

  Jack found a picture of the machine in the ocean book.

  He read:

  Scientists who study the ocean are called

  oceanographers[oʊʃənɒgrəfi].

  Sometimes they travel in small diving[ˈdaɪvɪŋ]

  vessels[ 'vesəlz ] called submersibles[səbmɜːʳsɪbəl],
  or "mini-subs," to study the ocean floor.

  "It's a mini-sub," said Jack, He pulled out his

  notebook.

  "Let's get inside it," said Annie.

  "No!" said Jack. Actually[ ˈæktʃuəli ], he did want to

  see what the sub looked like inside.

  But he shook his head. "We can't. It's not ours."

  "Just a teeny peek," said Annie.

  "It might help us figure out the riddle."

  Jack sighed. "Okay. But we have to be careful.

  Don't touch anything," he said.

  "Don't warry," said Annie.

  "And take off your shoes so they won't get wet," said

  Jack.

  He and Annie slipped[ slɪpt ] off their shoes and socks and

  threw them toward the tree house.

  Then they stepped carefully over the sharp

  coral[ ˈkɒrəl ].

  Annie turned the handle[ ˈhændl ] on the hatch[ hætʃ ]

  of the mini-sub.

  It opened.

  She and Jack climbed inside. The hatch

  slammed[ slæmd ] shut.

  The mini-sub was tiny. Two seats faced the big window.

  In front of the seats was a computer built into a

  control panel[ ˈpænl ].

  Annie sat down.

  Jack opened the ocean book and read more on the mini-sub

  page:

  Mini-subs have strong hulls[ hʌlz ] to keep air in and

  protect those aboard from water pressure.

  Computers are used to guide[ gaɪd ] the mini-sub

  through the ocean.

  "Oops," said Annie.

  "What's wrong?" Jack looked up.

  Annie was waving her hands in front of the computer.

  Now the screen showed a map.

  "What's going on?" said Jack.

  "I just pressed a few keys--" said Jack.

  An air blower[ ˈbləʊə(r) ] came on. The mini-sub

  jerked[ dʒə:kt ] backward.

  "Get out!" said Jack.

  He and Annie scrambled[ ˈskræmbld ] for the

  hatch[ hætʃ ].

  Jack grabbed the handle.

  But they were too late.

  The mini-sub slid[ slɪd ] off the reef[ ri:f ].

  Then it dove silently[ ˈsaɪləntli ] down into the deep.

  

  


* 3. Mini-sub
  "You've really done it now, Annie!" said Jack.

  "Sorry,sorry. But look out the window!" Annie said.

  "Look!"

  "Forget it! We have to figure[ ˈfɪgə(r) ] this out!"

  Jack stared at the computer.

  He saw a row of pictures at the top of the screen.

  "What did you do?" he asked.

  "I just pressed the ON button," said Annie.

  "The screen lit up. And I pressed the

  starfish[ ˈstɑ:fɪʃ ]."

  "That must be the command to go under the water,"

  said Jack.

  "Yeah. Then the map came on," said Annie.

  "Okay, okay. The map shows the reef," said Jack.

  "Look! There's the mini-sub on the map!

  It's moving away from the reef."

  "It's like a video game," said Annie.

  "I bet[ bet ] I know what to do."

  Annie pressed a key with an arrow pointing right.

  The mini-sub on the screen moved right.

  The real mini-sub turned to the right, also.

  "Great!" said Jack with relief[ rɪˈli:f ].

  "You press the arrows to steer[ stɪə(r) ] the mini-sub.

  So now we can go back."

  "Oh, no, not right away." said Annie.

  "It's so beautiful down here."

  "We have to get back to the reef," said Jack.

  His eyes were still glued[ ɡlu:d ] to the computer

  screen.

  "What if the owners find it gone."

  "Look out the window," said Annie. "Just for one

  teeny[ ˈti:ni ] second."

  Jack sighed. He pushed his glasses into place and

  looked up.

  "Oh, man," he said softly.

  Outside the glass was a strange world of bright moving

  color.

  It looked like another planet

  The mini-sub was moving past red,yellow,and blue coral

  --past little coral[ ˈkɒrəl ] mountains,

  valleys[ ˈvæliz ],and caves[ keivz ]--past fishes of

  every color and size.

  "Can't we stay a little while? The answer to Morgan's

  riddle must be here," said Annie.

  Jack nodded slowly. She might be right, he thought.

  Besides, when would they ever get to visit a place like

  this again?


  
* 4. Fish City

There were fish everywhere: floating over the

swaying[ sweiŋ ] sea grass, eating on the white

sandy[ ˈsændi ] bottom. peeping[ pi:pɪŋ ] out of

coral caves.
