#+STARTUP: overview

* 1 By Moonlight

"Jack!" whispered a voice.

Jack opened his eyes.He saw a figure[ˈfɪgə(r)] in

the moonlight.

"Wake up. Get dressed." It was his sister,Annie.

Jack turned on his lamp[ læmp ] . He rubbed[ 'rʌbd ] his

eyes.

Annie was standing beside his bed. She wore jeans[ dʒi:nz ]

and a sweatshirt[ ˈswetʃɜ:t ].

"Let's go to the tree house," she said.

"What time is it?" asked Jack. He put on his glasses.

"Don't look at your clock," said Annie.

Jack looked at his clock. "Oh, man,"he said. "It's midnight.

It's too dark."

"No, it isn't. The moon makes it bright enough to see,"

said Annie.

"Wait till morning," said Jack.

"No-now,"said Annie."We have to find the fourth M thing. I

have a feeling that the full moon might help us."

"That's nuts," said Jack. "I want to sleep."

"You can sleep when we come back home," said Annie. "No

time will have passed."

Jack sighed[ said ]. "Oh,brother,"he said.

But he got out of bed.

"Yay!" whispered[ 'wɪspəd ] Annie.

"Meet you at the back door." She tiptoed[ ˈtɪpˌtəʊd ]

out of Jack's room.

Jack yawned[ jɔ:nd ]. He pulled on his jeans[ dʒi:nz ]

and sneakers[ 'sni:kəz ] and a sweatshirt[ ˈswetʃɜ:t ].

He put his notebook and pencil into his backpack. Then

he crept[ krept ] down the stairs[ steəz ].

Annie opened the back door. Quietly, they stepped[ stept ]

outside.

"Wait--" said Jack. "We need a flashlight."

"No, we don't. I told you--the moon will light our way,"

said Annie. And she took off.

Jack sighed[ said ], then followed her.

Annie was right, thought Jack. The moon was so bright that

he could see his shadow. Everything seemed washed with

silver.

Soon they left their street. Annie led the way into

Frog Creek woods.

It was much darker under the shadows of the trees.

Jack looked up, searching for the tree house.

"There!" said Annie.

The magic tree house was shining in the moonlight.

Annie grabbed[ græbd ] the rope ladder and started

climbing up.

"Careful--go slowly," said Jack.

He followed her up the ladder and into the tree house.

Moonlight streamed through the window.

It shone on the letter M that shimmered[ ˈʃɪməd ] on

the wooden floor.

It shone on the three M things that rested on the M:

a Moonstone from the time of the ninjas, a mango from

the Amazon rain forest, and a mammoth bone from the Ice

Age.

"We need just one more M thing,"said Annie,"to

free Morgan from her spell."

Squeak.

"Peanut!" said Annie.

In the dim[ dɪm ] light, Jack saw a tiny mouse.

She sat on an open book.

"You didn't expect to see us this late did you?" said

Annie.

She picked up Peanut. And Jack picked up the open book.

"So where are win going this time?" Annie asked him.

Jack held the book up to the moonlight.

"Uh-oh," he said. "I knew we should have brought

a flashlight. I can't read a thing."

He could make out diagrams and shadowy[ ˈʃædəʊi ]

pictures. But he couldn't read a word.

"Look at the cover," said Annie.

The letters were bigger on the cover. Jack

squinted[ skwɪntid ] at them.

"It's called Hello,Moon," he said.

Annie gasped[ ɡɑ:spt ]. "We're going to the moon?"

"Of course not," said Jack."It's impossible to go to the

moon without tons[ tʌnz ] of equipment."

"Why?"

"There's no air. We couldn't breathe.Not only that,

we'd boil to death if it was day and freeze to death

if it was night."

"Yikes," said Annie. "So where do you think we are going?"

"Maybe a place where people train[ treɪn ] to be

astronauts[ 'æstrənɔ:ts ]," said Jack.

"That sounds neat," said Annie.

Jack opened the book again. He pointed to a picture of

a dome-shaped structure.

"I wish we could go there," he said.

The wind started to blow.

The tree house started to spin.

It spun faster and faster and faster.

Then everything was silent.

Absolutely silent. As quiet and still as silence could be.

* 2 Space Motle[ məʊˈtel ]

Jack opened his eyes.

He looked out the window. The tree house had landed

inside a large white room.

"What kind of training place is this?" asked Annie.

"I don't know," said Jack.

The room was round. It had no windows. It had white floors

and a curved[ kɜ:vd ] wall lit by bright lights.

"Hello!" Annie called.

There was no answer.

Where were all the astronauts[ 'æstrənɔ:ts ] and space

scientists[ 'saɪəntɪsts ]? Jack wondered.

"There's nobody here," said Annie.

"How do you know?" said Jack.

"I just feel it," said Annie.

"We'd better find out where we are," said Jack.

He looked at the page in the moon book. He read the words

below the picture of he dome[ dəʊm ].

A moon base was built on the moon in the year 2031.

The top of the dome slides[ s'laɪdz ] open to let

spacecrafts enter and leave.

"Oh,man--" Jack whispered.

"What's wrong?" said Annie.

Jack's heart pounded with excitement. He could hardly

speak. "We've landed inside a moon base," he said.

"So ...?" said Annie.

"So the moon base is on the moon!" said Jack.

Annie's eyes widened. "We're on the moon?" she asked.

Jack nodded. "The book says the moon base was built

in the year 2031," he said. "So this book was written

after that! Which means this book is from the futher!"

"Oh,Wow," said Annie. "Morgan must have gone forward

in time to borrow it from a future library."

"Right," said Jack. "And now we're in the future, on

the moon."

Squeak,squeak!

Annie and Jack looked at peanut. The mouse was running

around in circles.

"Poor Peanut," said Annie.

She tried to pick the mouse up.But Peanut hid behind the

mango on the letter M.

"Maybe she's nervous about being on the moon," said Annie.

"She's not the only one," said Jack. He let out a deep

breath, then he pushed his glasses into place.

"So what's a moon base?" asked Annie.

Jack looked at the book. He read aloud:

When scientists visit the moon for short periods, they eat

and sleep in the moon base.

"A space motel!!" said Annie.

"I guess," said Jack. He read more:

The small base has a landing chamber[ ˈtʃeɪmbə(r) ] and

a room for storing spacesuits. Air and temperature

controls make breathing possible.

"So that's why we can breathe," Jack said.

"Let's explore[ ɪkˈsplɔ:(r) ]," said Annie. "We have to

find the fourth thing for Morgan."

"No, first we should study this map," said Jack. He pulled

out his notebook.

"You study it," said Annie.

Jack copied the map. Then he drew in the tree house.

"Okay," he said. He pointed at the X in his drawing.

"We're here."

Jack looked up. Annie was gone.

"Oh brother," Jack said. As usual, she had left without

him. Before they could even make a plan.

Jack put the moon book and pencil into his pack. Carrying

his notebook and backpack, he started out the window.

Squeak! Squeak!

Jack looked back at peanut. The mouse was running back

and forth on the M.

"Stay here and be safe," said Jack. "We'll be back soon."

Jack swung himself over the window sill. His feet touched

the floor of the landing chamber.

"Annie!" he called.

There was no answer.

Jack looked at his diagram.

It showed only one way to go. Jack walked along the curved

white wall to the stairs.

He climbed the steps to a hallway.

"Jack-hurry!" Annie was at the end of the hallway,standing

in the airlock.

She peered[ piəd ] out a window in a giant[ ˈdʒaɪənt ]

door.

Jack hurried toward her. Annie stepped aside[ əˈsaɪd ] so

he could look out the window, too.

"Oh, man," said Jack. What he saw took his breath away.

He stared[ steərd ] at a rocky[ ˈrɒki ] gray land.

the land was filled with giant[ ˈdʒaɪənt ]

craters[ ˈkreitəz ] and tall mountains.

The sun was shining. But the sky was ink-black!

"Say hi to the moon," Annie said softly.

* 3 Open Sesame!
"The fourth M thing must be out there," said Annie.

Beside the door was a button with the word OPEN on it.

Annie reached for the button.

"Wait!" Jack grabbed[ græbd ] for her hand. "There's no

air on the mooon. Remember?"

"Oh. Right. But we have to go out to find the M thing."

"Let's see what the book says," said Jack.

He pulled the book out of his pack. He flipped[ flipt ]

through it until he found a page that showed the surface

of the moon. He read aloud:

It takes fourteen Earth days to equal one day on the moon.

No air protects the moon from the sun's rays, so daytime

heat reaches 260 degrees.

Jack looked at Annie. "I told you our blood would boil if

we went out there," he said.

"Yuck," she said.

Jack read from the book again:

Moon scientists wear spacesuits, which have controls to

keep them from getting too hot or too cold. They have

tanks, which provide air for two hours.

"Where do we get spacesuits?" asked Annie. She looked

around then trotted[ trɔtid ] back down the hall.

"Maybe there ...?"

Jack was studying his map. "Let's try the spacesuit

storeroom[ ˈstɔ:ru:m ]."

"Don't look at the map," said Annie. "Look at the real

room!"

Jack glanced[ ɡlɑ:nst ] up. Annie was peering[ piərɪŋ ]

through a doorway[ ˈdɔ:weɪ ] off the hall.

"There's a ton[ tʌn ] of space stuff[ stʌf ] in here!"

she said.

Jack went to look.

Bulky[ ˈbʌlki ] white suits[ sju:ts ] hung from

hangers[ 'hænɡəz ]. Air tanks, helmets[ ˈhelmits ],

gloves[ ɡ'lʌvz ], and boots[ bu:ts ] sat in neat[ ni:t ]

rows on shelves[ ʃelvz ].

"Wow, it's like the armor[ 'ɑ:mə ] room in a castle,"

said Jack.

"Yeah, with huge armor," said Annie.

"Let's pick out the smallest stuff," said Jack. "The

suits can go over our clothes."

Annie found the smallest white suit. And Jack found the

next smallest. They stepped into them.

Then Annie locked Jack's air tank into place.

"Thanks," he said. And he did the same for her.

"Thanks," she said.

"Gloves[ ɡ'lʌvz ]?" said Jack. He and Annie pulled

on white gloves[ ɡ'lʌvz ].

"Boots?" said Annie. They each pulled on a pair of huge

white boots.

"Helmets[ ˈhelmits ]?" said Jack. He reached for

a helmet[ ˈhelmits ].

"Wow,they're pretty light," he said. "I thought they'd be

like knights helmes."

Jack and Annie put he helmets on. They locked each other's

into place.

"I can't move my head right or left," said Annie.

"Me neither," said Jack. "Let's try walking."

Jack and Annie moved clumsily[ 'klʌmzɪlɪ ] around the

room.

Jack felt like a fat snowman.

"Close your visor," said Annie.

They both closed their see-through visors[ ˈvaizəz ].

Cool air filled Jack's helmet.

"I CAN BREATHE!" Annie yelled[ jeld ]. Her voice boomed in Jack's

ears.

"Ow! Talk quietly," Jack said. "We have two-way radios

inside our helmets."

"Sorry," whispered Annie.

Jack put the moon book back in his pack. Then he

slung[ slʌŋ ] the pack over his shoulder[ ˈʃəʊldə(r) ].

"Okay!" he said. "Remember, we only have two hours of

air in our tanks. So we need to find the fourth M

thing really fast."

"I hope we can find it," said Annie.

"Me too," said Jack. He knew they could not go home

until they did.

"Let's go," said Annie. She gave Jack a little push.

"Watch it. No goofing off," he said. "We don't want to

fall over in these suits."

"Just go--go!" said Annie. She pushed him out of the room.

They walked back to the airlock.

"Ready?" said Annie. "Open sesame[ ˈsesəmi ]!"

She pressed the OPEN button. A door slowly slid[ slɪd ]

closed behind them. A door opened in front of them.

And Jack and Annie stepped out onto the moon.









* 4 Moor Rabbits
"Oh,wow!" said Annie. She took astep forwad.

But Jack stood frozen[ ˈfrəʊzn ]. He wanted to get a good

look at everything first.

He stared[ steərd ] at the ground. He was standing in a


layer of gray dust[ dʌst ] as fine as powder[ ˈpaʊdə(r) ].

Footprints were everywhere. Jack wondered[ ˈwʌndə(r)d ]

who had made them.

He reached into his pack for the moon book. To his

surprise, it was as light as a feather!

He found a picture of footprints on the moon. He read:

The moon has no rain or wind to blow the dust around. So

footprints will never wear away naturally, not even in

billion years.

"Oh, man," Jack said.

The moon was the stillest[ stɪl ] place he had ever,

ever been. it was as still as a picture. And its

stillness would never, ever end.

Jack stared at the ink-black sky. A lovely blue-and-white

ball glowed far away.

Earth.

For the first time, it really hit Jack. They were in outer

space.

"Look!" Annie cried, laughing.

She bounded[ 'baʊndɪd ] past Jack--almost flying through

the air.

She landed on her feet. Then she jumped again.

Jack laughed. How does she do that? he wondered. He

turned a page and read:

A person weighs less on the moon because of the moon's

low gravity[ ˈgrævəti ] and lack of air. 

if you weigh 60 pounds on Earth, you would only weigh

10 pounds on the moon.

"Don't just stand there reading!" said Annie,grabbing

the book from Jack's gloved hand. She tossed[ tɒs ] it

into space.

The book had landed at the edge of a shallow[ ˈʃæləʊ ]

crater[ ˈkreɪtə(r) ].

When Jack reached it, he tried to stop. But his feet

slipped.

He fell right over and lay on his side. He tried to stand.

But he was off-balance.

He tried again. But the dust was just to deep.

And his spacesit was too clumsy.

"You okay?" asked Annie.

"I can't get up," said Jack.

"You shouldn't have been goofing off," said Annie wisely.

"You goofed off first," said Jack. "Now, help me up please."

Annie started toward him.

"Don't fall, too," warned Jack.

"I won't." Annie moved very slowly. She half floated,half

walked.

"Give me your hand." she said.

Annie grabbed Jack's hand. She pressed her boot against and

pulled him up.

"Thanks," he said.

"No problem," she said. "It was easy. You were really

light."

"Thank goodness," said Jack. "It's impossible to get up

alone."

He picked up the moon book. It was covered with dust.

He brushed it off.

"Oh, wow! Look!" said Annie. She stood at the edge of

the crater.

"What is it?" said Jack.

"A moon buggy!" said Annie.

The buggy was parked in the crater. It had four huge

wheels.

"Let's go for a ride," said Annie.

"We can't," said Jack. "We just have too hours of air in

our tanks. Remember?"

"I bet we'll find the M thing faster if we take the moon

buggy!" Annnie bounded[ 'baʊndɪd ] into the

crater[ ˈkreɪtə(r) ].

"But we can't driver!" said Jack.

"I bet I can drive this!" said Annie. "It looks easy.

Come on!"

She jumped into the driver's seat.

"But you don't have a license[ ˈlaɪsns ]!" said Jack.

"Who cares?" said Annie. "There aren't any roads on the

moon, or stoplights, or policemen either."

She was right, Jack thought.

"Well, go slow," he said. And he climbed in beside her.

Annie pushed a button labeled ON.

The moon buggy lurched[ lɜ:tʃ ] backward.

"Yikes!" said Annie.

"Step on the brake[ breɪk ]!" said jack.

Annie pressed a pedal[ ˈpedl ] on the floor. The buggy

stopped with a jerk[ dʒɜ:k ].

"Whew," she said.

"It must be in reverse[ rɪˈvɜ:s ]," said Jack. "Let me

study this--"

But before he could study anything, Annie pushed another

button.

The buggy tilted[ tɪltɪd ] back.

Its front wheels started to rise into the air.

"Let me out of here!" said Jack.

Annie pushed more buttons.

The buggy's front wheels landed back on the ground.

and the buggy leaped[ li:pt ] forward.

"Slower!" said Jack.

"I can't," said Annie. "I don't know how!"

Annie steered[ stiəd ] the buggy over the tracks[ træks ]

on the ground.

The wide wheels kept it from sinking[ 'sɪŋkɪŋ ] into the

deep dust.

"Careful" said Jack.

The buggy zoomed[ zu:md ] out of the crater.

Gray clouds of dust rose behind them as they toke off

across the moon.


* 5 Hang on
Annie drove the moon buggy over bumps[ bʌmps ] and

hollows[ 'hɒləʊz ].

It bucked[ bʌkt ] like a bronco[ ˈbrɒŋkəʊ ].

"I'm going through there!" She pointed to an opening

two mountains.

Jack held on to the dashboard.

The buggy bumped[ bʌmpt ] toward the opening and

shot through.

On the other side, the ground was even rockier.

"Look for the fo-fourth M thing!" said Annie, bouncing

up and down.

Jack groaned. Looking for anything on this wild ride

was impossible.

"Sl-slow d-down!" he said.

"How?"

"Try pressing on the brake[ breɪk ] pedal[ ˈpedl ]. On the

f-floor -slowly!"

Annie pressed on the brake.

The buggy slowed down. Jack sighed with relief[ rɪˈli:f ].

The ride wsa still bumpy.

But now ,at least, he could take a good look at the moon.

He had never been to such a colorless, barren[ ˈbærən ] place. There

was no green, no blue, no red.

No water, no trees, no clouds.

Only giant[ ˈdʒaɪənt ] gray rocks and craters[ ˈkreitəz ]

- and an American flag.

"Oh,man," said Jack. "That's from the first

astronauts[ 'æstrənɔ:ts ] who landed on the moon!"

"And look- a telescope[ ˈtelɪskəʊp ]!" said Annie.

She drove near the flag and telescope. Then she put her

foot on the brake until the buggy stopped.

She pressed a button that said OFF. Then she and jack

hopped [ hɔpt ] out.

They took slow giant[ ˈdʒaɪənt ] steps to the

site of the first moon landing.

Beside the flag was a sign[ saɪn ]. Annie read it aloud:

HERE MEN FROM THE PLANT EARTH

FIRST SET FOOT UPON THE MOON,

JULY 1969 A.D.

WE CAME IN PEACE

FOR ALL MANKIND[ mænˈkaɪnd ]. 

"That's a good message," said Jack.

He handed the moon book to Annie. Then he took out his

notebook and pencil to copy the sign.

"Let's leave our own message," said Annie.

"What should we say?" said Jack.

"The same thing," said Annie. "But say we are the

first kids."

Jack turned to a new page in his notebook. In big

letters he wrote their message.

"Now we have to sign it," Annie said.

Jack signed his name.

Then he passed the notebook and pencil to Annie.

She signed her name and passed the note book back.

Jak tore[ tɔ:(r) ] out the piece of paper. He put it

by the flag.

No wind would ever blow the message away.

No rain would ever fall on it.

It would be there forever,unless someone moved it.

Thinking of "forever" make Jack feel dizzy[ ˈdɪzi ].

He shook his head to clear his thoughts.
Then he remembered the time. Had two hours passwd yet?

"I wish i had a watch," he said, standing up.

"We might be running out of time."

"Oh, wow. A moon man!" said Annie.

"What?" Jack turned to look at her.

She was staring[ 'steərɪŋ ] through the telescope.

Jack walked over to the telescope.

Annie stepped aside so he could look,too

Jack gasped[ ɡɑ:spt ]. In the distance, something was

flying above the ground.

It looked like a giant[ ˈdʒaɪənt ] man in a spacesuit.

* 6 High jump
"Who is that?" said Jack.

"I don't know," said Annie. "But we'll soon find out!"

She started waving.

"No!"said Jack. He grabbed her arm. "Let's go back to

the base--before he gets here!"

"Why?" said Annie.

"We don't know who he is!" said Jack. "We don't know if

he's friendly or mean or what."

"But we can't go back," said Annie. "We haven't found

the fourth M thing yet. We won't be able to go home."

"It doesn't matter. We can lock the door at the moon

base until he goes away," said Jack. "Then we can

get new air tanks!"

Jack hurried to the moon buggy. "Come on!" He jumped

into the driver's seat.

Annie gave a little wave to the dot in the sky.

Then she climbed into the moon buggy.

The buggy took off.

"Careful!" said Annie.

They bumped over the rocks as Jack turned

the buggy around.

Then they zoomed toward the pass.

Jack steered arouond craters and rocks. More than once

the buggy nearly tipped[ 'tɪpt ] over.

"Whoa! Slow down!" said Annie.

They were almost at the  mountain pass.

Suddenly, a cloud of dust flew up in front of them.

The ground trembled[ ˈtrembld ].

"Watch it!" cried Annie.

Jack couldn't see a thing.

He stepped on the brake. THe buggy jerked[ dʒə:kt ]

to a stop.

The dust settled.

A giant rock had fallen into the narrow pass.

It was stuck[ stʌk ] between two walls of rock.

They were trapped[ træpt ]!

Jack quickly found a picture of a giant rock

in the moon book.

He read aloud:

Rocks of all sizes crash[ kræʃ ] into the moon

from outer space.

These rocks are called meteorites.

"We're lucky that meteorite didn't land on us,"said Jack.

"Yeah, and I guess it's too big to be the M thing,"

said Annie.

She had climbed out of the moon buggy and wsa standing

by the meteorite[ ˈmi:tiəraɪt ].

It was more than twice as tall as she was.

Jack looked at the black sky.

THe flying thing was nowhere in sight-yet.

"We'll have to jump over it," Annie said.

"Jump? I don't think so," said Jack. "It's to high."

"I'm going to try anyway," said Annie.

"Wait.Let's think first," said Jack.

But Annie was already backing up.

"One ,two, three--go!" she shouted, and took giant,

leaping steps toward the meteorite.

"Annie!" Jack called.

There was no answer.

"Oh, brother," Jack said. He backed up and took off

toward the rock.

He jumped as high as he could.

Then he was fling through space.

Jack hit the ground and fell facedown into the dust.

Jack tried to stand. But his suit was too bulky.

He tried to roll over.

But his suit made even that impossible.

"Oh, no," he groaned[ ɡrəund ]. "Not again."

"Are you here?" asked Annie."Did you make it?"

"Yes!" Jack was relieved to hear her voice.

But he couldn't turn his head to see her.

He could only hear her over the radio.

"Can you help me up?" he asked.

"Nope," said Annie.

"Why not?"

"I fell down, too." she said.

"Oh, brother," Jack sighed. "Now we are really in

trouble."

He tried to stand again. And failed.

"Can you see anything?" he asked.

"Just the sky," said Annie. "Wow, is it weird[ wɪəd ]..."

"I'm worried about our air tanks," said Jack. "I feel

like it's been two hours."

"Ja-ack..." said Annie.

"And what about that moon man?" said Jack.

"Where did he go to?"

"Jack!" whispered Annie.

"What?"

"He's here," she said. "The moon man is here."

"What?"

"He's standing above me."

* 7 The Moon Man
Jack's heart nearly stopped.

He could hear Annie talking.

"Hi," she said. "We come in peace."

There was silence[ ˈsaɪləns ]. Then Jack heard Annie say,

"Thank you, Ihave to help my brother up now."

A moment later, Annie rolled Jack onto his back.

She grabbed his hand and pulled him up.

"Thanks," said Jack, once he was standing.

The moon man was a few feet away. His face was hidden

by a metal visor.

He looked like a spaceman. A huge spaceman-with a

giant tank on his back.

It was as big as a refrigerator[ rɪˈfrɪdʒəreɪtə(r) ].

"Oh,right," said Jack. "I'll write him a message!"

"Good idea," said Annie.

Jack pulled out his notebook and pencil. He wrote:

We're Jack and Annie. We come in peacee from

American. Who are you ?

Jack handed the notebook and his pencil to the moon man.

They looked tiny in his big hands.

The moon man looked down at the message.

He looked at the tiny pencil.

Then he turned the notebook over.

Jack and Annie watched as the moon man put the pencil

to the paper.

He was writing something very carefully.

Finally he gave the notebook to Jack.

Jack and Annie stared at the marks.

"Stars," said Annie. "He drew stars."

"Mebe it's a space map," said Jack.

"Space map?" said Annie. "Hey, Jack, map starts with M!"

"Oh,wow," said Jack. "This must be the fourth M thing!"

"Let's ask him what his map means," said Annie.

She turned around.

"We'll never know now," she said.

"Why?" Jack looked up from the map.

"That's why." Annie pointed. The moon man was flying

over the mountains.

"Thanks!" Annie cried.

* 8 One star to another
"Who was that guy?" said Jack."What does his map mean?"

"I don't know," said Annie. "But let's see if it works."

Jack took a deep breath. "Yeah,we'd better hurry back.

I think I'm running out of air. It feels harder

to breathe."

"For me, too," said Annie.

"Go slow. Don't breathe too much," said Jack.

He and Annie took long, floating steps toward the

moon base.

Jack held his breathe as if he were underwater.

By the time they got to the white dome[ dəʊm ],

he was ready to burst[ bɜ:st ].

Annie pushed a button beside the huge door.

it slid[ slɪd ] open.

They hurried into the airlock.

The door closed behind them and the door to the

hallway opened.

Jack opened the visor[ ˈvaɪzə(r) ] of he

helmet[ ˈhelmɪt ].

He took a long,deep breath--and let it out. "Ahhhh!"

"Let's get out of these suits," said Annie.

"Good idea." Jack was dying[ ˈdaɪɪŋ ] to free

his arms and legs.

As they moved clumsily[ 'klʌmzɪlɪ ] into the spacesuit

storeroom, Jack felt heavy again.

He and Annie unlocked each other's helmets,

gloves[ ɡ'lʌvz ], and boots, and pulled everything off.

Then they stepped out of their bulky[ ˈbʌlki ] suits.

"Whew!" Jack said. He took off his glasses and

rubbed[ 'rʌbd ] his eyes.

It was great to be free--even if he no longer

felt as light as a feather.

"Hurry! Peanut's waiting!" said Annie.

She led the way down the steps to the bright

landing chamber[ ˈtʃeɪmbə(r)].

"Yay," she said softly.

Jack was relieved to see the tree house still there.

Soon they'd be heading[ ˈhedɪŋ ] home.

He couldn't wait.

Jack and Annie crawled[ krɔ:ld ] through the tree

house window.

"We're back, Peanut!" said Annie.

She patted[ pætid ] the mouse's head. "We met a

moon man."

"Sorry, Peanut, but you have to move," said Jack.

"We have to put the map on the M."

Annie gently[ ˈdʒentli ] lifted[ liftid ] the mouse

off the M.

Jack tore the star map out of his notebook.

He placed it on the M, next to the mammoth bone,

the mango, and the moonstone.

He sighed, then sat back on his hells.

"Hand me the Pennsylvania book," he said.

They needed the Pennsylvania book to get back home.

There was silence.

Jack turned and looked at Annie.

"It's not working, Jack," she said. "The

book's not here."

"What?" Was the map the wrong thing?

They looked around the tree house.

"It's definitely[ ˈdefɪnətli] not here," said Annie.

"Oh, no." Jack's heart sank[ sæŋk ].

He picked up the star map and stared[ steərd ] at it.

Squeak,squeak. Peanut jumped out of Annie's arms

and scurried back to the letter M.

"I've got an idea," said Jack. He reached into his pack

and took out his pencil.

"What are you doing?" said Annie.

"You know how you draw a constellation[ ˌkɒnstəˈleɪʃn ]?"

said Jack.

"You connect all the stars. What happens if we try that?"

He drew a line from one star to another.

He kept drawing, until all the stars were connected.

"Let me see," said Annie.

Jack held the paper out so they could both study it.

"It looks like a mouse," said Annie.

"Yeah," said Jack.

"Is there such a thing as a mouse

constellation[ ˌkɒnstəˈleɪʃn ]?" said Annie.

"I don't think so ..." said Jack.

Squeak.

Annie and Jack looked at Peanut. She was standing

on the M.

"Oh, wow. Jack," Annie whispered,"I think I know

what the fourth thing is-"

Jack grinned. "Me too," he said "It's a -"

"Mouse!" they said together.

Squeak! Squeak!

"Maybe the spell is--Moonstone,mango,mammoth bone,

mouse!" said Annie.

Jack touched each M thing in turn as he whispered,

"Moonstone, mango, mammoth bone, mouse."

"Let's say it over and over and see what happens,"

said Annie.

Together, they chanted[ tʃɑ:ntid ]:

"Moonstone,mango,mammoth bone,mouse.

Moonstone,mango,mammonth bone,mouse."

Suddenly, a bright light filled the tree house.

The light got brighter and brighter and brighter.

The brightness was blinding and whirling[ 'wɜ:lɪŋ ].

The air spun with brightness.

Then everything was clear.

Peanut the mouse was gone.

And Morgan le Fay stood before Jack and Annie.




* 9 Morgan
"Thank you," Morgan said softly. "You have freed me from

the magician[ məˈdʒɪʃn ]'s spell"

Jack just stared at her.

"You were Peanut?" Annie said.

Morgan nodded and smiled.

"Really? You were with us all the time?" said Jack.

"On all our missions?"

Morgan nodded again.

"Why did we have to go on this mission to find a mouse?"

said Jack. "If you were always with us?"

"To break the spell, we had to be on the moon," said

Morgan. "You could have broken it the minute  we arrived."

"Oh, that's what Peanut--I mean you were try to say!"

said Annie.

"We didn't have to leave the moon base at all."

Morgan nodded, smiling.

"But the moon man came along to help us,"said Annie

"He drew a constellation[ ˌkɒnstəˈleɪʃn ] of a mouse!

Is he a friend of yours?"

Morgan shrugged.

"Let's just say we had a little talk. He stopped by

the moon base while you were out."

"The same way you had a talk with the ninja[ ˈnɪndʒə ]

master, right?" said Jack. "And the monkey and

the sorcerer[ ˈsɔ:sərə(r) ]?"

Morgan nodded. "I always squeaked to the ones

who helped you."

"But how did they understand you -- a mouse?" said Jack.

Morgan smiled again. "Certain wise ones understand the

language of little creatures," she said.

"I bet it was you who turned the pages of the books!"

said Annie. "To show us where to go next!"

Morgan nodded.

"But who turned you into a mouse?" said Annie.

Mogan frowned[ fraund ].

"A certain person who likes to play tricks[ trɪks ] on

me," she said. "His name is Merlin."

"Merlin!" said Jack. "The greatest magician[ məˈdʒɪʃn ]

who ever lived."

Morgan sniffed[ snift ].

"He's not that great," she said. "He doesn't even know

I have two brave friends who help me."

"Us?" said Annie shyly[ ʃaɪlɪ ].

Morgan nodded. "And I thank you both with all my heart."

"You're welcome," said Jack and Annie.

Mogan handed Annie the Pennsylvania book.

"Are you ready to go home now?" she asked.

"Yes!" said Jack and Annie.

Annie pointed to a picture of the Frog Creek woods.

"I wish we could go there," she said.

The tree house started to spin.

It spun faster and faster and faster.

Then everything was still.

Absolutely still.

But only for a moment.



* 10 Earth life
The midnight woods woke up.

A breeze[ bri:z ] rustled[ ˈrʌsld ] the leaves.

An owl[ aʊl ] hooted[ hu:tid ].

The sounds were soft, but very alive.

Jack opened his eyes. He pushed his glasses into place.

He smiled. Morgan was still with them.

He could see her in the moonlight.

Her long while hair was shining.

"Morgan, can you and the tree house stay her?" said

Annie. "In Frog Creek"

"No, I must leave again, I'm afraid," said Morgan.

"I've been gone from Camelot for a long time."

She handed Jack his pack. She brushed his cheek[ tʃi:k ].

Her hand felt soft and coll.

"A bit of moondust still on you," she said.

"Thank you, Jack, for your great love of knowledge."

"You're welcome," said Jack.

Morgan tugged[ tʌɡd ] on one of Annie's braids[ breɪdz ].

"And thank you, Annie, for your belief in the

impossible."

"You're welcom," said Annie.

"Go home now," said Morgan.

Jack smiled. Home was Earth--that bright,colorful world

where everything was alive and always changing.

"Bye,Morgan," said Annie. She started out of the

tree house.

Jack looked back at Morgan.

"Will you come back soon?" he said.

"Anything can happen," said Morgan.

"The universe[ ˈju:nɪvɜ:s ] is filled with

wonders[ 'wʌndəz ].Isn't it, Jack?"

He smilled and nodded.

"Go now," Morgan said softly.

Jack followed Annie down the rope ladder.

He stepped onto the ground.

The wind started to blow.

The tree started to shake.

A loud roar filled Jack's ears.

He squeezed[ skwi:zd ] his eyes shut.

He covered his ears.

Then everything was silent and still.

Jack opened his eyes. The ladder was gone.

He looked through the leaves and branches

of the giant[ ˈdʒaɪənt ] oak tree.

Where the tree house had been was only moonlight now.

"Bye,Morgan," he whispered sadly.

"Bye, Peanut," said Annie.

Jack and Annie stared[ steərd ] at the top of

the tree for along moment.

"Ready?" said Annie.

Jack nodded.

They started for home.

The midnight air felt cool and moist[ mɔɪst ].

It was filled with the soft sounds of earth life.

Jack and Annie left the Frog Creek woods.

They started down their street.

Annie glanced[ ɡlɑ:nst ] up at the sky.

"The moon looks really far away, doesn't it?"

It did, Thought Jack. It was.

"I wonder how the moon man can be up there all alone,"

said Annie.

"What do you mean?" said Jack.

"I mean, whe helps him put on his spacesuit?" said Annie.

"Who helps him get up when he falls down?"

"And who is he?" added Jack.

"Who do you think he was?" said Annie.

"He must be a scientist[ ˈsaɪəntɪst ] or an

astronaut[ ˈæstrənɔ:t ] from Earth." said Jack.

"No. I think he's an alien," said Annie, "from another

galaxy[ ˈgæləksi ]."

Jack scoffed[ skɔft ]. "What makes you say that?"

"I just feel it," said Annie.

"Wrong," said Jack. "There's no proof that

aliens[ ˈeiljənz ] exist."

"Maybe not now," said Annie. "But don't forget-

we were in the future."

"Oh, brother," said jack.

They crossed their yard[ jɑ:d ] and climbed their

back steps. Annie tiptoed[ ˈtɪpˌtəʊd ] inside the house.

Jack followed her.

Before he shut the door, he glanced[ ɡlɑ:nst ] up at

the moon.

Was Annie right? he wondered. Could the moon man have

come from an other galaxy?

Morgan's word come back to him: The universe is filled

with wonders.

Isn't it, Jack?

"Goodnight, moon man," Jack whispered. Then he closed

the door.
