#+startup: overview
#+title: Linux_Shell脚本攻略
#+author: dream

* 第五章 B计划
** 6.1 简介
提取快照和备份数据都是我们的日常工作.就服务器或大型数据存储系统而言,
定期备份不可小视.我们可以通过shell脚本来实现备份自动化.归档和压缩对
系统管理员或普通用户来说平日里都少不了用到.有许多不同的压缩格式,要结
合不同的使用方法才可以获得最佳的压缩效果.加密是另一种保护数据的常用方法.
为了减少加密数据的大小,文件在加密之前通常都要先进行归档和压缩.有许多标准
加密算法可以使用,并且它们都有相应的shell工具.本章考查了这方面的各类
攻略,包括创建和维护文件或文件夹归档,压缩格式以及加密技术.接下来让我们
看看这些内容.
** 6.2 用tar归档
tar命令可以用来归档文件.不过,它最初是设计用来将数据存储在磁带上(tape
archives, tar).可以用tar将多个文件和文件夹保存为单个文件,同时还能
保留所有的文件属性,如所有者,权限等.由该命令创建的文件通常称为tarball.

*** 6.2.1 预备知识
所有类unix操作系统都默认包含tar命令.它的语法简单,并且文件格式具备
可移植性.让我们来看看命令的用法.

tar包含一个参数列表: A,c,d,r,u,x,f和v.其中每一个参数都可以依据不同
的用途单独使用.

*** 6.2.2 实战演练
按照下面的语法,用tar对文件进行归档:
tar -cf output.tar [SOURCES]
例如:
  tar -cf output.tar file1 file2 file3 folder1...
  命令中的-c代表"创建文件"(create file), -f代表"指定文件名"
  (specify filename)

我们可以使用文件名列表或者诸如*.txt这类通配符来指定文件夹和文件名作为
sources.

上面的命令将原文件归档为单个文件output.tar.
文件名必须紧跟在-f 之后,并且应该是参数组中的最后一项
(例如,-cvvf filename.tar和-tvvf filename.tar).

我们不能传递上百个文件或文件夹作为tar的参数,毕竟参数数量不是无限制的.
如果有很多文件需要归档的话,我们使用追加(append) 选项要更安全些.

*** 6.2.3 补充知识
让我们再来看看tar命令的其他特性.
1. 向归档文件中添加文件
   有时候,我们可能需要向已存在的归档文件再添加一些文件(其用例情境包括
   :当有成百上千个文件需要归档且这些文件又无法作为命令行参数在一行中
   指定时).
   追加选项: -r
   要向已存在的归档文件添加一个文件,可以使用:
     tar -rvf original.tar new_file

   用下面方法列出归档文件中的内容:
   #+begin_src bash
     tar -tf archive.tar
   #+end_src

   如果需要在归档或列出归档内容的过程中获知更多细节,可以使用-v或
   -vv选项.它们统称为verbose(v),它们允许在终端中输出更详细的信息,
   借助verbose,你能够打印诸如文件权限,所有者所属组,文件修改日期等
   细节.
   例如:
   #+begin_src bash
     tar -tvvf archive.tar
   #+end_src

2. 从归档文件中提取文件或文件夹
   下面的命令将归档文件的内容提取到当前目录中:
   #+begin_src bash
     tar -xf archive.tar
   #+end_src
   选项-x时,tar命令将归档文件中的内容提取到当前目录.
   我们也可以用选项-C指定需要将文件提取到哪个目录:

   #+begin_src bash
     tar -xf archive.tar -C /path/to/extraction_directory
   #+end_src

   这个命令将归档文件的内容提取到指定目录中.它提取的是归档文件中的全
   部内容.我们可以通过将文件名指定为命令行参数来提取特定的文件:

   #+begin_src bash
     tar -xvf file.tar file1 file4
   #+end_src

   上面的命令只提取file1和file4,同时忽略掉其他文件.

3. 在tar中使用stdin和stdout
   
